### PR TITLE
Improved Makefile.

### PR DESCRIPTION
**Pull request by darkdragon-001**
Added targets: all, uninstall
Masked non-file targets as PHONY

### CODE REVIEW

**Comment by N-Yuki** [comment]
Thanks for the pull request. The workflow is changed a bit with this.
`make` would previously produce the zip package, but now it just does the "compilation". Now that the zip package is not the first item, I assume the zip file will only be built when the full zip file name is entered as the target. If we are making this change, can we at least add a new target like `package`that produces the zip file too.
We could also split it out into a shell script if we have an argument for that.

Anyway, what do you think? Am I misunderstanding anything?

Otherwise, the rest of the changes look good.

**Comment by darkdragon-001** [comment]
Since there was no documentation on how to use this, I didn't get the point of the zip file. Have I seen this correctly, that it is not used for installation but only for distribution?

And what about the schemas? There is no `...gschema.xml` present and thus the `schema` target fails...

**Comment by N-Yuki** [comment]
Yes, the zip file is for distribution. It is the only format that the gnome extension website accepts.

You are correct. There used to be a schema file when I had some configurable options, but I must've removed them at some point, but didn't remove them completely from the makefile. Please feel free to remove them from the makefile. Also, let's just keep only `compile` by depending on the zip file and remove the `package` target, so we don't have too many layers for indirection. I will merge after this final change.

Thanks for doing this.

**Comment by darkdragon-001** [comment]
I removed schema generation.

Also, are you fine in naming the zip generation _package_ instead of _compile_ since it might lead to confusion (people think that you have to compile before being able to install)?

**Comment by N-Yuki** [comment]
Good point.

Looks good. I will merge this.

**Pull request merged**
